version: '3'
services:
  backend:
    build: ./backend
    ports: 
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
    restart: always
  frontend:
    build: ./frontend
    ports: 
      - "8080:8080"
    depends_on:
      - backend 
    restart: always